- alias: Dan
  name: Daniel Beiting
  role: Research Assistant Professor
  twitter: hostmicrobe
  github: dpbisme
  web: hostmicrobe.github.io
  avatar: headshot.jpg
  email: danielbeiting@gmail.com
  phone: +1-215-898-9247
  fax: +1-215-746-2295
  address: University of Pennsylvania, Rm 314 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "I am an immunologist using 'omics approaches to interroage the host-pathogen interface. I am the technical director for the Center for Host-Microbial Interactions at PennVet."
